language: php

env:
    global:
        - PHPUNIT_FLAGS="-v"

php:
    - "7.0"
    - "7.1"
    - "7.2"

install:
    - composer install

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS